# Generated by Django 2.0.7 on 2018-08-16 21:41

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.upload_path_handler),
        ),
    ]
