# Generated by Django 2.0.7 on 2018-08-23 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_class', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': "Age - Classes d'ages",
                'verbose_name': "Age - Classe d'ages",
            },
        ),
        migrations.CreateModel(
            name='Age_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.CharField(default=1, max_length=3)),
                ('age_max', models.CharField(default=1, max_length=3)),
                ('age_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Age_Group', to='activities.Age_Class')),
            ],
            options={
                'verbose_name_plural': "Age - Groupes d'ages",
                'verbose_name': "Age - Groupe d'ages",
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='noimage.jpg', upload_to='images/events/')),
                ('time_start', models.TimeField(null=True)),
                ('time_end', models.TimeField(null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('number_max', models.PositiveSmallIntegerField()),
                ('number_available', models.PositiveSmallIntegerField(null=True)),
                ('age_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event', to='activities.Age_Group')),
            ],
            options={
                'verbose_name_plural': 'Eléments',
                'verbose_name': 'Elément',
            },
        ),
        migrations.CreateModel(
            name='Event_Subtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_subtype', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/event_subtype')),
            ],
            options={
                'verbose_name_plural': 'Eléments - Sous-types',
                'verbose_name': 'Eléments - Sous-type',
            },
        ),
        migrations.CreateModel(
            name='Event_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ACTIVITY', 'ACTIVITY'), ('TRAININGCOURSE', 'TRAININGCOURSE'), ('EVENT', 'EVENT')], max_length=50)),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/event_type')),
            ],
            options={
                'verbose_name_plural': 'Eléments - Types',
                'verbose_name': 'Eléments - Type',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='RegistrationList', to='activities.Event')),
                ('participant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='RegistrationList', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inscriptions',
                'verbose_name': 'Inscription',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('image', models.ImageField(default='noimage.jpg', upload_to='images/hosts/')),
                ('resume', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Animateurs',
                'verbose_name': 'Animateur',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Niveaux',
                'verbose_name': 'Niveau',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Périodes',
                'verbose_name': 'Période',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Salles',
                'verbose_name': 'Salle',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street_nb', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.IntegerField()),
                ('iframe_url_map', models.URLField(max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Lieux',
                'verbose_name': 'Lieu',
            },
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Jours',
                'verbose_name': 'Jour',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Room', to='activities.Venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event', to='activities.Weekday'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event', to='activities.Event_Subtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event', to='activities.Event_Type'),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event', to='activities.Host'),
        ),
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event', to='activities.Level'),
        ),
        migrations.AddField(
            model_name='event',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event', to='activities.Period'),
        ),
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event', to='activities.Room'),
        ),
    ]
