# Generated by Django 2.0.7 on 2018-08-24 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('time_start', models.TimeField(null=True, verbose_name='Heure de début')),
                ('time_end', models.TimeField(null=True, verbose_name='Heure de fin')),
                ('description', models.TextField(verbose_name='Description')),
                ('rate_resident_1_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('rate_resident_1', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Tarif MC 1')),
                ('rate_resident_2_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('rate_resident_2', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Tarif MC 2')),
                ('rate_non_resident_1_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('rate_non_resident_1', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Tarif hors MC 1')),
                ('rate_non_resident_2_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('rate_non_resident_2', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Tarif hors MC 2')),
                ('notes', models.TextField(verbose_name='Notes particulières')),
            ],
            options={
                'verbose_name_plural': 'Activités',
                'verbose_name': 'Activité',
            },
        ),
        migrations.CreateModel(
            name='Age_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_class', models.CharField(max_length=100, verbose_name="Classe d'age")),
            ],
            options={
                'verbose_name_plural': "Age - Classes d'ages",
                'verbose_name': "Age - Classe d'ages",
            },
        ),
        migrations.CreateModel(
            name='Age_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.IntegerField(verbose_name='Age minimum')),
                ('age_max', models.IntegerField(verbose_name='Age maximum')),
                ('age_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Age_Group', to='activities.Age_Class')),
            ],
            options={
                'verbose_name_plural': "Age - Groupes d'ages",
                'verbose_name': "Age - Groupe d'ages",
            },
        ),
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('image', models.ImageField(default='noimage.jpg', upload_to='images/animation/', verbose_name='Image')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Animations',
                'verbose_name': 'Animation',
            },
        ),
        migrations.CreateModel(
            name='Animation_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animation_type', models.CharField(max_length=100, verbose_name="Type d'animation")),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/animation_type', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Animations - Types',
                'verbose_name': 'Animation - Type',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
            ],
            options={
                'verbose_name_plural': 'Villes',
                'verbose_name': 'Ville',
            },
        ),
        migrations.CreateModel(
            name='Elements_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('ACTIVITY', 'ACTIVITY'), ('TRAININGCOURSE', 'TRAININGCOURSE'), ('EVENT', 'EVENT')], max_length=50, verbose_name="Type d'élément")),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Label')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/event_type', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Eléments - Types',
                'verbose_name': 'Eléments - Type',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, null=True, verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('initials', models.CharField(max_length=10, null=True, verbose_name='Initiales')),
                ('image', models.ImageField(default='noimage.jpg', upload_to='images/hosts/', verbose_name='Image')),
                ('resume', models.TextField(null=True, verbose_name='Présentation')),
            ],
            options={
                'verbose_name_plural': 'Animateurs',
                'verbose_name': 'Animateur',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100, verbose_name='Niveau')),
            ],
            options={
                'verbose_name_plural': 'Niveaux',
                'verbose_name': 'Niveau',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20, verbose_name='Période')),
            ],
            options={
                'verbose_name_plural': 'Périodes',
                'verbose_name': 'Période',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100, verbose_name='Salle')),
            ],
            options={
                'verbose_name_plural': 'Salles',
                'verbose_name': 'Salle',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('street_nb', models.CharField(max_length=20, verbose_name='N°')),
                ('street_name', models.CharField(max_length=200, verbose_name='Rue')),
                ('postcode', models.IntegerField(verbose_name='Code Postal')),
                ('iframe_url_map', models.URLField(max_length=500, null=True, verbose_name='URL Google Iframe')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Venue', to='activities.City')),
            ],
            options={
                'verbose_name_plural': 'Lieux',
                'verbose_name': 'Lieu',
            },
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=10, verbose_name='Jour')),
            ],
            options={
                'verbose_name_plural': 'Jours',
                'verbose_name': 'Jour',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Room', to='activities.Venue'),
        ),
        migrations.AddField(
            model_name='animation',
            name='animation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Animation', to='activities.Animation_Type'),
        ),
        migrations.AddField(
            model_name='activityslot',
            name='age_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Activity', to='activities.Age_Group'),
        ),
        migrations.AddField(
            model_name='activityslot',
            name='animation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Activity', to='activities.Animation'),
        ),
        migrations.AddField(
            model_name='activityslot',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Activity', to='activities.Weekday'),
        ),
        migrations.AddField(
            model_name='activityslot',
            name='host',
            field=models.ManyToManyField(related_name='Activity', to='activities.Host'),
        ),
        migrations.AddField(
            model_name='activityslot',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Activity', to='activities.Level'),
        ),
        migrations.AddField(
            model_name='activityslot',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Activity', to='activities.Period'),
        ),
        migrations.AddField(
            model_name='activityslot',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Activity', to='activities.Room'),
        ),
    ]
