# Generated by Django 2.0.7 on 2018-07-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='noimage.jpg', upload_to='images')),
                ('day', models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], max_length=2)),
                ('time_start', models.TimeField(auto_now=True, null=True)),
                ('time_end', models.TimeField(auto_now=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('number_max', models.PositiveSmallIntegerField()),
                ('age_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='event', to='activities.Age_Group')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Subtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_subtype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street_nb', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.PositiveSmallIntegerField()),
                ('url_map', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='room', to='activities.Venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_subtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='event', to='activities.Event_Subtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='event', to='activities.Event_Type'),
        ),
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='event', to='activities.Level'),
        ),
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='event', to='activities.Room'),
        ),
    ]
