# Generated by Django 2.0.7 on 2018-07-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.TimeField(null=True),
        ),
    ]
