# Generated by Django 2.0.7 on 2018-08-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityslot',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='host',
            field=models.ManyToManyField(null=True, related_name='Activity', to='activities.Host'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='notes',
            field=models.TextField(null=True, verbose_name='Notes particulières'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='rate_non_resident_1_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Désignation Tarif hors MC 1'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='rate_non_resident_2_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Désignation Tarif hors MC 2'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='rate_resident_1_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Désignation Tarif MC 1'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='rate_resident_2_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Désignation Tarif MC 2'),
        ),
    ]
