# Generated by Django 2.0.7 on 2018-08-24 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20180824_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='noimage.jpg', upload_to='images/animation/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
            },
        ),
        migrations.CreateModel(
            name='Animation_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animation_type', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/animation_type')),
            ],
            options={
                'verbose_name': 'Animation - Type',
                'verbose_name_plural': 'Animations - Types',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Ville', 'verbose_name_plural': 'Villes'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_subtype',
        ),
        migrations.RemoveField(
            model_name='event',
            name='host',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='host_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event_host_1', to='activities.Host'),
        ),
        migrations.AddField(
            model_name='event',
            name='host_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event_host_2', to='activities.Host'),
        ),
        migrations.AddField(
            model_name='event',
            name='host_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event_host_3', to='activities.Host'),
        ),
        migrations.AddField(
            model_name='event',
            name='host_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event_host_4', to='activities.Host'),
        ),
        migrations.AddField(
            model_name='event',
            name='host_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event_host_5', to='activities.Host'),
        ),
        migrations.AddField(
            model_name='host',
            name='initials',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='number_max',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='Event_Subtype',
        ),
        migrations.AddField(
            model_name='animation',
            name='animation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Animation', to='activities.Animation_Type'),
        ),
        migrations.AddField(
            model_name='event',
            name='animation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event', to='activities.Animation'),
        ),
    ]
