# Generated by Django 2.0.7 on 2018-08-24 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20180824_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityslot',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Activity', to='activities.Age_Group'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Activity', to='activities.Weekday'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='host',
            field=models.ManyToManyField(blank=True, related_name='Activity', to='activities.Host'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes particulières'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Activity', to='activities.Period'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='rate_non_resident_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tarif hors MC 1'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='rate_non_resident_1_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Désignation Tarif hors MC 1'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='rate_non_resident_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tarif hors MC 2'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='rate_non_resident_2_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Désignation Tarif hors MC 2'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='rate_resident_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tarif MC 1'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='rate_resident_1_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Désignation Tarif MC 1'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='rate_resident_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tarif MC 2'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='rate_resident_2_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Désignation Tarif MC 2'),
        ),
    ]
