# Generated by Django 2.0.7 on 2018-08-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20180824_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='initials',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
