# Generated by Django 2.0.7 on 2018-07-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20180708_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='images/events/'),
        ),
    ]
