# Generated by Django 2.0.7 on 2018-08-25 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20180824_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityslot',
            name='age_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Activity', to='activities.Age_Group'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='activityslot',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de début'),
        ),
    ]
