# Generated by Django 2.0.7 on 2018-08-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20180824_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animation',
            options={'verbose_name': 'Animation', 'verbose_name_plural': 'Animations'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='rate',
        ),
        migrations.AddField(
            model_name='event',
            name='rate_non_resident',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Tarif hors MC'),
        ),
        migrations.AddField(
            model_name='event',
            name='rate_resident',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Tarif MC'),
        ),
        migrations.AlterField(
            model_name='age_class',
            name='age_class',
            field=models.CharField(max_length=100, verbose_name="Classe d'age"),
        ),
        migrations.AlterField(
            model_name='age_group',
            name='age_max',
            field=models.IntegerField(verbose_name='Age maximum'),
        ),
        migrations.AlterField(
            model_name='age_group',
            name='age_min',
            field=models.IntegerField(verbose_name='Age minimum'),
        ),
        migrations.AlterField(
            model_name='animation',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='images/animation/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='animation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='animation_type',
            name='animation_type',
            field=models.CharField(max_length=100, verbose_name="Type d'animation"),
        ),
        migrations.AlterField(
            model_name='animation_type',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='animation_type',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/animation_type', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_available',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Nb places libres'),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_max',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Nb max participants'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.TimeField(null=True, verbose_name='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.TimeField(null=True, verbose_name='Heure de début'),
        ),
        migrations.AlterField(
            model_name='event_type',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event_type',
            name='event_type',
            field=models.CharField(choices=[('ACTIVITY', 'ACTIVITY'), ('TRAININGCOURSE', 'TRAININGCOURSE'), ('EVENT', 'EVENT')], max_length=50, verbose_name="Type d'élément"),
        ),
        migrations.AlterField(
            model_name='event_type',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/event_type', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='event_type',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='host',
            name='firstname',
            field=models.CharField(max_length=100, null=True, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='host',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='images/hosts/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='host',
            name='initials',
            field=models.CharField(max_length=10, null=True, verbose_name='Initiales'),
        ),
        migrations.AlterField(
            model_name='host',
            name='lastname',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='host',
            name='resume',
            field=models.TextField(null=True, verbose_name='Présentation'),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(max_length=100, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.CharField(max_length=20, verbose_name='Période'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.CharField(max_length=100, verbose_name='Salle'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='iframe_url_map',
            field=models.URLField(max_length=500, null=True, verbose_name='URL Google Iframe'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='postcode',
            field=models.IntegerField(verbose_name='Code Postal'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='street_name',
            field=models.CharField(max_length=200, verbose_name='Rue'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='street_nb',
            field=models.CharField(max_length=20, verbose_name='N°'),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='day',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=10, verbose_name='Jour'),
        ),
    ]
