# Generated by Django 2.0.7 on 2018-07-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='images/hosts/'),
        ),
    ]
