# Generated by Django 2.0.7 on 2018-07-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_host_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='resume',
            field=models.TextField(null=True),
        ),
    ]
