# Generated by Django 2.0.7 on 2018-07-31 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0010_auto_20180709_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='RegistrationsList', to='activities.Event')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='RegistrationsList', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
