# Generated by Django 2.0.7 on 2018-07-31 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0011_registrationslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationslist',
            name='user',
        ),
        migrations.AddField(
            model_name='registrationslist',
            name='user',
            field=models.ManyToManyField(related_name='RegistrationsList', to=settings.AUTH_USER_MODEL),
        ),
    ]
