# Generated by Django 2.0.7 on 2018-07-31 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_auto_20180731_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationslist',
            name='event',
        ),
        migrations.RemoveField(
            model_name='registrationslist',
            name='user',
        ),
        migrations.DeleteModel(
            name='RegistrationsList',
        ),
    ]
