# Generated by Django 2.0.7 on 2018-08-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_auto_20180731_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_type',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
