# Generated by Django 2.0.7 on 2018-08-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_event_type_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_subtype',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
