# Generated by Django 2.0.7 on 2018-08-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_auto_20180808_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_subtype',
            name='event_subtype',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event_type',
            name='event_type',
            field=models.CharField(choices=[('ACTIVITY', 'ACTIVITY'), ('TRAININGCOURSE', 'TRAININGCOURSE'), ('EVENT', 'EVENT')], max_length=10),
        ),
    ]
