# Generated by Django 2.0.7 on 2018-08-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_auto_20180808_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_type',
            name='img_src',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='event_type',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event_type',
            name='event_type',
            field=models.CharField(choices=[('ACTIVITY', 'ACTIVITY'), ('TRAININGCOURSE', 'TRAININGCOURSE'), ('EVENT', 'EVENT')], max_length=50),
        ),
    ]
