# Generated by Django 2.0.7 on 2018-08-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_auto_20180809_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_subtype',
            name='img_src',
            field=models.URLField(null=True),
        ),
    ]
