# Generated by Django 2.0.7 on 2018-08-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0020_event_subtype_img_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number_available',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
