# Generated by Django 2.0.7 on 2018-08-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0022_eventregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_type',
            name='title',
        ),
    ]
