# Generated by Django 2.0.7 on 2018-08-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0023_remove_event_type_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventregistration',
            old_name='events',
            new_name='event',
        ),
    ]
