# Generated by Django 2.0.7 on 2018-08-10 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0024_auto_20180810_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='RegistrationList', to=settings.AUTH_USER_MODEL),
        ),
    ]
