# Generated by Django 2.0.7 on 2018-08-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0027_auto_20180813_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_type',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event_type',
            name='event_type',
            field=models.CharField(choices=[('ACTIVITY', 'ACTIVITY'), ('TRAININGCOURSE', 'TRAININGCOURSE'), ('', 'EVENT')], max_length=50),
        ),
    ]
