# Generated by Django 2.0.7 on 2018-08-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0028_auto_20180813_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='url_map',
        ),
        migrations.AddField(
            model_name='venue',
            name='iframe_url_map',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event_type',
            name='event_type',
            field=models.CharField(choices=[('ACTIVITY', 'ACTIVITY'), ('TRAININGCOURSE', 'TRAININGCOURSE'), ('EVENT', 'EVENT')], max_length=50),
        ),
    ]
