# Generated by Django 2.0.7 on 2018-08-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0029_auto_20180816_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='postcode',
            field=models.IntegerField(),
        ),
    ]
