# Generated by Django 2.0.7 on 2018-08-10 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0021_event_number_available'),
        ('accounts', '0002_profile_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='RegistrationList', to='activities.Event')),
                ('participant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='RegistrationList', to='accounts.Profile')),
            ],
        ),
    ]
