# Generated by Django 2.0.7 on 2018-08-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_registrationlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationlist',
            name='events',
        ),
        migrations.RemoveField(
            model_name='registrationlist',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='events',
        ),
        migrations.DeleteModel(
            name='RegistrationList',
        ),
    ]
