# Generated by Django 2.0.7 on 2018-08-25 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0004_auto_20180825_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nom')),
                ('level', models.TextField(blank=True, null=True, verbose_name='Niveau')),
                ('dates', models.TextField(blank=True, null=True, verbose_name='Dates')),
                ('date_of_the_last_day', models.DateField(verbose_name='Date du dernier jour')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes particulières')),
                ('rate', models.TextField(blank=True, null=True, verbose_name='Tarifs')),
                ('age_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Workshop', to='activities.Age_Group')),
                ('animation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Workshop', to='activities.Animation')),
                ('host', models.ManyToManyField(blank=True, related_name='Workshop', to='activities.Host')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Workshop', to='activities.Room')),
            ],
            options={
                'verbose_name': 'Atelier',
                'verbose_name_plural': 'Ateliers',
            },
        ),
    ]
